name: moiami
services:
  resource:
    image: trard/moiami_resource_service:1.0
    restart: unless-stopped
    expose:
      - "8000"
    environment:
      SECRET_KEY: 'django-insecure-o&+f#_3gh5d^t=00y37i$$l!)&g44@)_g$$e0#=ourvm2g_l3w)2'
      DEBUG: true
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - static_files:/app/staticfiles
  caddy:
    image: caddy:2
    restart: unless-stopped
    depends_on:
      - resource
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - static_files:/srv/staticfiles
  sso:
    image: leoagf/sso:1.2
    restart: unless-stopped
    ports:
      - "3533:8001"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: 'postgresql+asyncpg://postgres:postgres@db:5432/postgres'
      SECRET_KEY: 'M&6u_hdJ-)Qvx:yGkN+2|1a917e3c181d9399a72327e00f78ff8a9992aeea|3ae318fbdc247ce171ea90c244cc46e4'
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "1234:5432"
    environment:
      DB_URL: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data2:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
  s3:
    image: quay.io/minio/minio:latest
    restart: unless-stopped
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  static_files:
  postgres_data2:
  minio_data:

